[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["dash14 <dash14.ack@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.104.0"
pydantic = "^2.4.2"
uvicorn = "^0.23.2"
pykakasi = "^2.2.1"
pyokaka = "^1.0.0"
python-multipart = "^0.0.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
